### ISSUE TITLE
Way to configure name of the runner

### ISSUE THREAD

**Issue by Divyansh42** [redhat-actions/openshift-self-hosted-runner#2]
I am trying to configure name of the runner as `test-runner` as follows:
``` 
helm install runner-test ./runner-charts/deployment \
    --set-string githubOwner=divyansh42 \
    --set-string githubRepository=s2i-build
```
Output: 
```
NAME: runner-test
LAST DEPLOYED: Mon Jan 18 18:47:54 2021
NAMESPACE: diagrawa-code
STATUS: deployed
REVISION: 1
TEST SUITE: None

oc get pods -w                                                                                                    
NAME                      READY   STATUS              RESTARTS   AGE
runner-6bf9856869-htc2x   0/1     ContainerCreating   0          4s
runner-6bf9856869-htc2x   0/1     ContainerCreating   0          4s
runner-6bf9856869-htc2x   1/1     Running             0          9s
```

But still name of the runner as shown on the UI of the giithub is `runner-6bf9856869-htc2x`
In my opinion it should be something `runner-test-xxxxxxx-xxx` as name of the runner is `runner-test`

**Comment by tetchel** [comment]
the name of the deployment is determined by the `appName` value. which could have a better name now that the deployment is its own chart. 

```
helm install runner-test ./runner-charts/deployment \
    --set-string githubOwner=divyansh42 \
    --set-string githubRepository=s2i-build
    --set appName="runner-test"
```

will do what you want. though, I will rename it do `deploymentName`.

**Comment by Divyansh42** [comment]
Okay, Thanks.
Also fine with the `appName` though. :sweat_smile: 
Didn't knew this earlier.

**Comment by tetchel** [comment]
i just got confused by this too.
