### ISSUE TITLE
Error downloading helm

### ISSUE THREAD

**Issue by gfvirga** [redhat-actions/openshift-self-hosted-runner#5]
Hi,

I was trying out to use setup-helm using the base runner and I am getting the error `Error: Error: Parameter 'commandLine' cannot be null or empty` I couldn't find the root cause this is happening, but it might be related to the dependencies in the fedora base image as this doesn't happen in the ubuntu base image.

I was able to replicate the error in a sandbox environment - https://github.com/gfvirga/testactions/runs/1737626965?check_suite_focus=true

Thank you,
Gabe Virga

**Comment by tetchel** [comment]
that's a strange error. I don't see any message like that in the action you used.

You could try installing helm by hand: 
```
wget -q https://get.helm.sh/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
    && tar -xf helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
```

Also, in general, when debugging Actions, you can create a secret `ACTIONS_STEP_DEBUG` to `true` to see debug output. But, inspecting that action it has very little output so that won't help you here.

https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging

**Comment by tetchel** [comment]
I am considering switching to UBI so I don't want to dig too much into the fedora thing.

**Comment by gfvirga** [comment]
Thanks for the quick reply and workaround, I am going to try that out.

I was able to install the openshift-cli, but I didn't see the option to add helm there.

I added the secret for debbuging and didn't really see the error anywhere. I also rsh to the container and didn't see much that could help.




> I am considering switching to UBI so I don't want to dig too much into the fedora thing.
I tried using UBI in the past and due to the the yum repo limitations it was hard to download all the dependencies correctly, I kind off got it to work.

**Comment by tetchel** [comment]
> I was able to install the openshift-cli, but I didn't see the option to add helm there.

https://github.com/redhat-actions/openshift-cli-installer#supported-clis

You can install helm with the following workflow yaml:
```
steps:
  - name: Install Helm
    uses: redhat-actions/openshift-cli-installer@v1
    with:
      - helm: 3
```

**Comment by jduimovich** [comment]
As a data point - I tested your  blank.yml on my CentOS Stream action
runner and it worked. Totally different environment than the container
based runner but wanted to see if it worked at all.
If I have a chance to try it on the base runner I'll post the results here.

**Comment by gfvirga** [comment]
@tetchel, the job that was in the github workflows was https://github.com/redhat-actions/oc-installer and it points to references `uses: redhat-actions/oc-installer@v1`

I tried loading the one you suggested and it did not work. It's saying that `with:` with multiple options 
 -"Invalid type found: map was expected but an array was found"

**Comment by tetchel** [comment]
Sorry, I guess you have to quote the version. And for the openshift-cli-installer, it's just `oc` instead of `oc_version`.

So:
```yaml
with:
  - helm: "3"
  - oc: "4"

**Comment by gfvirga** [comment]
@tetchel, this is great, worked perfectly! https://github.com/gfvirga/testactions/runs/1738771561?check_suite_focus=true
